image: hashicorp/terraform:1.7

stages:
  - validate
  - plan
  - apply

before_script:
  - terraform --version
  - terraform init -input=false

validate:
  stage: validate
  script:
    - terraform validate
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

plan:
  stage: plan
  script:
    - terraform plan -input=false -out=tfplan
  artifacts:
    paths:
      - tfplan
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

apply:
  stage: apply
  script:
    - terraform apply -input=false -auto-approve tfplan
  dependencies:
    - plan
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == "main"